//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by HtmlForgeX Icon Generator.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     Generation Date: {GENERATION_DATE}
//     Icon Count: {ICON_COUNT}
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace HtmlForgeX;

/// <summary>
/// SVG-based icon element with full styling and positioning control.
/// Replaces the old CSS-based TablerIcon system with native SVG rendering.
/// </summary>
public partial class TablerIconElement : Element {
    public TablerIconType Icon { get; set; }
    private TablerIcon _svgIcon;

    public TablerIconElement(TablerIconType icon) {
        Icon = icon;
        _svgIcon = TablerIconLibrary.GetIcon(icon);
    }

    /// <summary>
    /// Set the stroke color of the SVG icon
    /// </summary>
    public TablerIconElement Color(RGBColor color) {
        _svgIcon.StrokeColor(color);
        return this;
    }

    /// <summary>
    /// Set the size of the SVG icon (width and height)
    /// </summary>
    public TablerIconElement FontSize(int size) {
        _svgIcon.Size(size);
        return this;
    }

    /// <summary>
    /// Set the stroke width of the SVG icon
    /// </summary>
    public TablerIconElement StrokeWidth(double width) {
        _svgIcon.StrokeWidth(width);
        return this;
    }

    /// <summary>
    /// Set the fill color of the SVG icon
    /// </summary>
    public TablerIconElement FillColor(RGBColor color) {
        _svgIcon.FillColor(color);
        return this;
    }

    /// <summary>
    /// Add custom CSS style to the SVG icon
    /// </summary>
    public TablerIconElement AddStyle(string property, string value) {
        _svgIcon.AddStyle(property, value);
        return this;
    }

    /// <summary>
    /// Rotate the SVG icon by specified degrees
    /// </summary>
    public TablerIconElement Rotate(int degrees) {
        _svgIcon.Rotate(degrees);
        return this;
    }

    /// <summary>
    /// Scale the SVG icon by specified factor
    /// </summary>
    public TablerIconElement Scale(double factor) {
        _svgIcon.Scale(factor);
        return this;
    }

/// <summary>
/// Method ToString.
/// </summary>
    public override string ToString() {
        return _svgIcon.ToString();
    }
}