    /// <summary>Gets the "home" icon.</summary>
    /// <summary>Gets the "user" icon.</summary>
    /// <summary>Gets the "settings" icon.</summary>
    /// <summary>Gets the "search" icon.</summary>
    /// <summary>Gets the "heart" icon.</summary>
    /// <summary>Gets the "star" icon.</summary>
    /// <summary>Gets the "check" icon.</summary>
    /// <summary>Gets the "x" icon.</summary>
    /// <summary>Gets the "plus" icon.</summary>
    /// <summary>Gets the "minus" icon.</summary>
